import type { Metadata } from "next"
import Providers from '@/components/Providers'
import TopNav from '@/components/navbar/TopNav'
import "./globals.css"

export const metadata: Metadata = {
  title: "nextMatch",
  description: "Generated by create next app",
};

// layout applied to all pages
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <TopNav />
          <main className='container mx-auto'>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
